use_frameworks!

platform :ios, '10.0'

target 'ZLUIKitPlus_Example' do
  pod 'ZLUIKitPlus', :path => '../'

  target 'ZLUIKitPlus_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
