use_frameworks!


platform :ios, '13.0'

target 'ZLUIKitPlus_Example' do
  pod 'ZLUIKitPlus', :path => '../'
  pod 'Masonry'
  pod 'Then'
  pod 'SDWebImage'
  pod 'ZLFlexKit', :path => '../../ZLFlexKit'
  

  target 'ZLUIKitPlus_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
